name: 'entr'
version: '0.1.0'

require-dbt-version: [">=1.3.0", "<2.0.0"]

config-version: 2

profile: 'entr'

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  entr:
    +materialized: view

vars:
  dim_entr_asset_models: ['int_dim_entr_asset__structured']
  dim_entr_tag_list_models: ['int_dim_entr_tag_list__structured', 'seed_entr_tag_list']
  fct_entr_time_series_models: ['int_fct_entr_time_series__structured']
