name: 'entr'
version: '0.1.0'
config-version: 2

profile: 'entr'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  entr:
    +materialized: view

seeds:
  entr:
    examples:
      +enabled: false

vars:
  dim_asset_reanalysis_dataset_models: ['int_dim_asset_reanalysis_dataset__structured']
  dim_asset_wind_plant_models: ['int_dim_asset_wind_plant__structured']
  dim_asset_wind_turbine_models: ['int_dim_asset_wind_turbine__structured']
  fct_entr_plant_models: ['int_fct_entr_plant_data__structured']
  fct_entr_wtg_scada_models: ['int_fct_entr_wtg_scada__structured']
  fct_entr_reanalysis_models: ['int_fct_entr_reanalysis_data__structured']
