name: 'entr_integration_tests'
version: '0.1.0'
config-version: 2

profile: 'integration_tests'

model-paths: ["models"]
seed-paths: ["seeds"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_packages"

seeds:
  +quote_columns: false

vars:
    entr:
        dim_entr_asset_models: [seed_asset_plant, seed_asset_wind_turbine]
        fct_entr_time_series_models: [stg_entr_era5_sample, stg_entr_merra2_sample, stg_entr_plant_sample, stg_entr_scada_sample]
